name: Run MATLAB Tests on GitHub-Hosted Runner

permissions: read-all

on: # yamllint disable-line rule:truthy
  push:
  pull_request:
    branches:
      - main

jobs:
  run-tests:
    name: Checkout, Compile and Test
    runs-on: ubuntu-latest
    permissions:
      checks: write
      pull-requests: write

    steps:
      - name: Check out paper repository
        uses: actions/checkout@v3
        with:
          path: paper

      - name: Check out libDirectional repository
        uses: actions/checkout@v3
        with:
          repository: libDirectional/libDirectional
          path: libDirectional

      - name: Set up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install Python dependencies
        run: |
          pip install pytorch-lightning matplotlib scipy

      - name: Set up MATLAB
        uses: matlab-actions/setup-matlab@v1

      - name: Add lib directory to path and compile
        uses: matlab-actions/run-command@v1
        with:
          command: "addpath(genpath('libDirectional')); compileAll;"

      - name: Run MATLAB script
        uses: matlab-actions/run-command@v1
        with:
          command: "addpath(genpath('paper'));cd('paper/Evaluation');evaluateForAllShapes;paperPlots;exit(isempty(lasterr))"
